version: '3.9'

services:
  db:
    container_name: postgresql
    image: postgres:13-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=hubladb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
